---

- name: Check if Jira service is running
  shell: docker service ls | awk '{print $2}' | grep jira
  ignore_errors: true
  register: jira_status
  changed_when: jira_status.rc == 1
  failed_when: jira_status.rc == 2

- name: Retrieve password from vault
  connection: local
  hashivault_read:
    secret: 'service/database/postgres'
    key: 'password'
  register: postgres_password
  when: jira_status.rc == 1

- name: Set fact to carry database secret
  connection: local
  set_fact:
    postgres_password: "{{lookup('hashivault', 'service/database/postgres', 'password')}}"
  when: jira_status.rc == 1

- name: Set fact to carry jira database secret
  connection: local
  set_fact:
    jira_db_password: "{{lookup('hashivault', 'service/jira', 'jira_db_password')}}"
  when: jira_status.rc == 1


- name: Create jira db user
  connection: local
  postgresql_user:
    login_host: postgres
    login_password: '{{postgres_password}}'
    user: jira
    password: "{{ jira_db_password }}"
    encrypted: "yes"
    state: present
  when: jira_status.rc == 1

- name: Setup nextcloud database on db server
  connection: local
  postgresql_db:
    login_host: postgres
    login_password: '{{postgres_password}}'
    name: jira-prod
    owner: jira
    state: present
  when: jira_status.rc == 1


- name: Deploy jira service
  command: >
    docker service create -d --name jira
    --network mangonet
    --label traefik.port=8080
    --label traefik.enable=true
    --replicas 1
    --mount type=bind,source=/var/lib/ca-certificates/pem,target=/etc/ssl/certs
    --mount 'type=volume,"volume-opt=o=addr=files.sysmango.net,vers=4.1",volume-opt=device=:/srv/nfs/prod/jira/data,volume-opt=type=nfs,target=/var/atlassian/application-data/jira'
    -e ATL_PROXY_NAME=jira.sysmango.net
    -e ATL_JDBC_URL=jdbc:postgresql://postgres:5432/jira-prod
    -e ATL_DB_DRIVER=org.postgresql.Driver
    -e ATL_DB_SCHEMA_NAME=public
    -e ALT_JDBC_USER=jira
    -e ALT_JDBC_PASSWORD={{ jira_db_password }}
    -e ATL_TOMCAT_SCHEME=https
    -e ATL_TOMCAT_SECURE=true
    -e JVM_SUPPORT_RECOMMENDED_ARGS=-Djavax.net.ssl.trustStore=/var/atlassian/application-data/jira/jira.jks
    registry.sysmango.net/atlassian/jira-software:8.8.0-jdk11
  run_once: true
  when: jira_status.rc == 1

# --mount type=bind,src=/srv/docker-volumes/jira/data,dst=/var/atlassian/jira \
# --mount type=bind,src=/srv/docker-volumes/jira/logs,dst=/opt/atlassian/jira/logs \

# --mount 'type=volume,"volume-opt=o=addr=files.sysmango.net,vers=4.1",volume-opt=device=:/srv/nfs/prod/jira/data,volume-opt=type=nfs,target=/var/atlassian/jira'
# --mount 'type=volume,"volume-opt=o=addr=files.sysmango.net,vers=4.1",volume-opt=device=:/srv/nfs/prod/jira/logs,volume-opt=type=nfs,target=/var/atlassian/jira/logs'
# jiraVolume:/var/atlassian/application-data/jira
